# AdGuard Home + Unbound
/etc/adguardhome/
/etc/unbound/
/overlay/adguardhome/

# panici.casa DNS automation
/etc/crontabs/root
/usr/bin/pve-dns-sync.sh
/usr/bin/udm-dns-sync.sh
/usr/bin/panici-ptr-sync.sh
/usr/bin/panici-dns-sync
/root/.ssh/
